import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/nav/nav-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} px-32 py-16 flex flex-col gap-20`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
